// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { Suspense } from "react";
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// }); 
 
// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <Suspense fallback={<div>Loading</div>}>


//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//     </Suspense>
//   );
// }


// import { AuthProvider } from '@/context/AuthContext'
// import './globals.css'
// import { Suspense } from 'react'
// import ForceLightMode from '@/components/ForceLightMode'
// import { Metadata } from 'next';

// export const metadata: Metadata = {
//   title: "Invitation",
//   description: "Voici votre lien pour obtenir une invitation à mon mariage",
//   openGraph: {
//     title: "Invitation",
//     description: "Voici votre lien pour obtenir une invitation à mon mariage",
//     url: "https://invitationmariage.vercel.app", // Remplacez par votre URL
//     type: "website",
//     images: [
//       {
//         url: "/danz.png", // Chemin relatif depuis le dossier public
//         width: 1200,
//         height: 630,
//         alt: "Description de l'image",
//       },
//     ],
//   },
//   twitter: {
//     card: "summary_large_image",
//     title: "Votre Titre pour Twitter",
//     description: "Description pour Twitter",
//     images: ["/danz.png"],
//   },
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <Suspense fallback={<div>Loading...</div>}>
//     <html lang="fr" className="force-light-mode" data-mode="light">
//        <head>
//         {/* Balises meta personnalisées */}
//       </head>
//       <body>
//         <ForceLightMode />
//         <AuthProvider>{children}</AuthProvider>
//       </body>
//     </html>
//     </Suspense>
//   )
// }

import { AuthProvider } from '@/context/AuthContext'
import './globals.css'
import ForceLightMode from '@/components/ForceLightMode'
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Invitation",
  description: "Voici votre lien d'invitation à notre mariage",
  openGraph: {
    title: "Invitation",
    description: "Voici votre lien  d'invitation à notre mariage",
    url: "https://moninvitation.vercel.app",
    type: "website",
    images: [
      {
        url: "https://i.ibb.co/y9bwy52/couple-picture.webp",
        width: 1200,
        height: 630,
        alt: "Description de l'image",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Votre Titre pour Twitter",
    description: "Description pour Twitter",
    images: ["https://i.ibb.co/y9bwy52/couple-picture.webp"],
  },
};
// URLSearchParams
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fr" className="force-light-mode" data-mode="light">
      <head>
         <link rel="preload" href="/couple.jpg" as="image" />
        <link rel="preload" href="/wed-day.webp" as="image" />
        <link rel="preload" href="/ecal.webp" as="image" />
        <link rel="preload" href="/deco.webp" as="image" />
        <link rel="preload" href="/fleure-deco.webp" as="image" />
        <link rel="preload" href="/couple-picture-3.webp" as="image" />
        {/* Autres balises meta... */}
     
        <link rel="preload" href="https://i.ibb.co/5WqS64p9/couple-picture-3.webp" as="image" />
      </head>
      <body>
        
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  )
}